foreground              #f0e6e6
background              #1a1016

selection_foreground    #1a1016
selection_background    #3e2e34

cursor                  #f5e0dc
cursor_text_color       #1a1016

active_tab_foreground   #f0e6e6
active_tab_background   #1a1016
inactive_tab_foreground #6c7086
inactive_tab_background #130b0e
tab_bar_background      #1a1016

active_border_color     #4e6e4e
inactive_border_color   #3e2e34

color0  #1a1016
color8  #4e3e44
color1  #8e4e5e
color9  #ac6e7e
color2  #4e6e4e
color10 #6e8e6e
color3  #aead8e
color11 #ceceae
color4  #6e8eae
color12 #8eaece
color5  #8e6e8e
color13 #ae8eae
color6  #6eaeae
color14 #8ecece
color7  #cdd6f4
color15 #f0e6e6
